latexmlc \
  --preload=[nobibtex,ids,localrawstyles,mathlexemes,magnify=2,zoomout=2,tokenlimit=99999999,iflimit=1499999,absorblimit=1299999,pushbacklimit=599999]latexml.sty \
  --path=/opt/arxmliv-bindings/bindings \
  --path=/opt/arxmliv-bindings/supported_originals \
  --format=html5 \
  --pmml \
  --cmml \
  --mathtex \
  --timeout=2700 \
  --nodefaultresources \
  --css=https://cdn.jsdelivr.net/gh/dginev/ar5iv-css@0.7.4/css/ar5iv.min.css \
  --source=main.tex \
  --destination=html/main.html \
  --javascript=main.js
